### ISSUE TITLE
Getting error: ShuttingDown:, logs don't contain much info

### ISSUE THREAD

**Issue by weeryan17** [nikshriv/cync_lights#39]
Hello I hope your doing well,

Today I ran into an issue where this integration will log `ShuttingDown:`, nothing else and it doesn't work.
This screenshot is from the home assistant log interface
![image](https://user-images.githubusercontent.com/10491247/213330569-441b207e-5018-4e9a-8bef-9add8a28e41a.png)
I noticed the line it's referencing is it connecting to the cync servers so it could just be possible their down, although the actual cync app on my phone works fine.
I'll keep checking if the integration starts working, either way you should probably improve the logging.

**Comment by nikshriv** [comment]
ShuttingDown usually occurs if you uninstall, reload, or reconfigure the integration. You can probably just ignore that error message. Hopefully, the integration is still working for you.

**Comment by weeryan17** [comment]
Sadly it is not working for me, I'm unable to control my smart plug, and I have a felling #40 is having the same issue, the log message did only pop up after a home assistant update so maybe it's hiding the true issue.

**Comment by weeryan17** [comment]
Acctuly I just check the logs again and I found this, so maybe this is the true issue 
![image](https://user-images.githubusercontent.com/10491247/215883480-19fb5bed-cad5-4e25-9fa8-edd28bd80003.png)

**Comment by nikshriv** [comment]
That is helpful. It looks like the integration is not picking up any connected devices. I have seen this happen with some of my bulbs as well but can't figure out why these Cync devices behave this way sometimes.  I may have a workaround, so I'll let you know when it's fixed.

**Comment by nikshriv** [comment]
I make a small change which will default to using the switch id of the device if there are no other detected connected devices. Hopefully that will fix your issue. Let me know if it works for you.

**Comment by weeryan17** [comment]
I'm no longer getting any errors from the integration, but sadly it's still not working.
I did get this error, but it looks like this is from home assistant it's self.
![image](https://user-images.githubusercontent.com/10491247/216391717-bd8a85c3-89f9-4289-9af5-d4e41ab57bcc.png)

**Comment by nikshriv** [comment]
This means that your plug is not responding to WiFi commands. I have had this problem with some of my bulbs as well, but I'm still able to control them with the integration because I have a number of other WiFi connected bulbs that are connected and functioning, so the commands go through them. It is a Cync issue, and I cannot figure out how to get those bulbs to properly connect to my WiFi. Did you have trouble getting the plug device to connect to your WiFi when you were setting it up?  To test my theory, try disabling the bluetooth on your phone and then try to control the plug with the Cync app. If the device doesn't respond to commands from the app with bluetooth disabled, you have a WiFi connection problem.

You might try deleting the device from your Cync system and reinstalling it. Hopefully it will properly connect if you try again.

**Comment by weeryan17** [comment]
Oh your right, I disabled wifi and it can't control it via the cync app any more, that is weird, I didn't have any issues connecting it to wifi initially, that is super weird, guess I need to reset my plug. You should probably implement logging just saying that home assistant can't connect to the device via wifi as to lessen the confusion. Thank you for your help!

**Comment by nikshriv** [comment]
For those that have many devices, logging that information would probably clog your logs. These Cync devices are pretty unreliable and don't always stay connected, unfortunately. That was the reason I had to implement checking for connected devices in the first place. If you can't get it to work over WiFi, there is an integration that uses bluetooth to connect to the devices instead of WiFi.

**Comment by weeryan17** [comment]
I would recommend adding something to the readme then at the very least, something along the lines of "If you are having connectivity issues in home assistant, but the app works, try turning of bluetooth and check if the app still works, if it doesn't you need to reconnect your device to wifi". Considering there where 3 issues posted on this probably bets to have the information somewhere.

Anyways thank you again so much for the help and I know if it stops working in the future it's probably cause the device got disconnected from wifi

**Comment by nikshriv** [comment]
That’s a good suggestion. I’ll update it soon

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by elliotmatson** [comment]
@nikshriv So interestingly I can confirm that my plug is connected to WiFi, and is controllable with Home Assistant. Just all the bluetooth bulbs connected to the plug don't work from Home Assistant
