### ISSUE TITLE
Error message

### ISSUE THREAD

**Issue by marc3k18** [nikshriv/cync_lights#44]
Detected integration that called async_setup_platforms instead of awaiting async_forward_entry_setups; this will fail in version 2023.3. Please report issue to the custom integration author for tuya using this method at custom_components/tuya/__init__.py, line 136: hass.config_entries.async_setup_platforms(entry, PLATFORMS)

**Comment by marc3k18** [comment]
Wrong repo! Sorry 👯

**Comment by mcarsten6** [comment]
I did receive this error for cync_lights:
 Logger: homeassistant.helpers.frame
Source: helpers/frame.py:77
First occurred: 7:00:51 PM (1 occurrences)
Last logged: 7:00:51 PM
Detected integration that called async_setup_platforms instead of awaiting async_forward_entry_setups; this will fail in version 2023.3. Please report issue to the custom integration author for cync_lights using this method at custom_components/cync_lights/__init__.py, line 19: hass.config_entries.async_setup_platforms(entry, PLATFORMS)
