### ISSUE TITLE
Cync account credentials

### ISSUE THREAD

**Issue by Pvtjoker77** [nikshriv/cync_lights#5]
I log in then it sends the 2 factor verification code but when I enter it I get "Unknown error occurred while retrieving Cync configuration"
<img width="454" alt="Screen Shot 2022-09-04 at 4 52 49 PM" src="https://user-images.githubusercontent.com/51425835/188334902-f538c5b8-416b-4bde-bc2b-eaeb537d029b.png">

**Comment by Pvtjoker77** [comment]
I did log out of the App and log back in just to make sure the username and password were correct.

**Comment by nikshriv** [comment]
Please check your log and see if there is an error reported there. Post that and I we'll take a look

**Comment by StevenSeiden** [comment]
Here is the error that I received:
`Unexpected exception
Traceback (most recent call last):
  File "/config/custom_components/cync_lights/config_flow.py", line 104, in async_step_two_factor_code
    info["data"]["cync_config"] = await self.cync_hub.get_cync_config()
  File "/config/custom_components/cync_lights/config_flow.py", line 239, in get_cync_config
    room_controller = home_controllers[home_id][0]
IndexError: list index out of range`

I previously had two "homes" in my Cync account, but after deleting one, the issue was resolved, and I was able to login properly.

**Comment by nikshriv** [comment]
Thanks, I'll put in a filter for empty homes...
